//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestNetLogEntry.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestNetLogEntry.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Items&quot;:[
        ///{ &quot;id&quot;:128049154, &quot;Name&quot;:&quot;gold&quot;, &quot;BuyPrice&quot;:9111, &quot;SellPrice&quot;:8925, &quot;MeanPrice&quot;:9373, &quot;StockBracket&quot;:2, &quot;DemandBracket&quot;:0, &quot;Stock&quot;:923, &quot;Demand&quot;:1, &quot;Consumer&quot;:false, &quot;Producer&quot;:true, &quot;Rare&quot;:false },
        ///{ &quot;id&quot;:128049155, &quot;Name&quot;:&quot;silver&quot;, &quot;BuyPrice&quot;:4496, &quot;SellPrice&quot;:4402, &quot;MeanPrice&quot;:4759, &quot;StockBracket&quot;:2, &quot;DemandBracket&quot;:0, &quot;Stock&quot;:1538, &quot;Demand&quot;:1, &quot;Consumer&quot;:false, &quot;Producer&quot;:true, &quot;Rare&quot;:false },
        ///{ &quot;id&quot;:128049156, &quot;Name&quot;:&quot;bertrandite&quot;, &quot;BuyPrice&quot;:0, &quot;SellPrice&quot;:2660, &quot;MeanPrice&quot;:2486, &quot;StockBr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string market {
            get {
                return ResourceManager.GetString("market", resourceCulture);
            }
        }
    }
}
