//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestNetLogEntry.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestNetLogEntry.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Items&quot;:[
        ///{ &quot;id&quot;:128049154, &quot;Name&quot;:&quot;gold&quot;, &quot;BuyPrice&quot;:9111, &quot;SellPrice&quot;:8925, &quot;MeanPrice&quot;:9373, &quot;StockBracket&quot;:2, &quot;DemandBracket&quot;:0, &quot;Stock&quot;:923, &quot;Demand&quot;:1, &quot;Consumer&quot;:false, &quot;Producer&quot;:true, &quot;Rare&quot;:false },
        ///{ &quot;id&quot;:128049155, &quot;Name&quot;:&quot;silver&quot;, &quot;BuyPrice&quot;:4496, &quot;SellPrice&quot;:4402, &quot;MeanPrice&quot;:4759, &quot;StockBracket&quot;:2, &quot;DemandBracket&quot;:0, &quot;Stock&quot;:1538, &quot;Demand&quot;:1, &quot;Consumer&quot;:false, &quot;Producer&quot;:true, &quot;Rare&quot;:false },
        ///{ &quot;id&quot;:128049156, &quot;Name&quot;:&quot;bertrandite&quot;, &quot;BuyPrice&quot;:0, &quot;SellPrice&quot;:2660, &quot;MeanPrice&quot;:2486, &quot;StockBr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Modules&quot;:[ 
        ///{ &quot;Slot&quot;:&quot;MainEngines&quot;, &quot;Item&quot;:&quot;int_engine_size5_class1&quot;, &quot;Power&quot;:4.080000, &quot;Priority&quot;:0 }, 
        ///{ &quot;Slot&quot;:&quot;Slot01_Size5&quot;, &quot;Item&quot;:&quot;int_shieldgenerator_size5_class5&quot;, &quot;Power&quot;:3.640000, &quot;Priority&quot;:0 }, 
        ///{ &quot;Slot&quot;:&quot;TinyHardpoint6&quot;, &quot;Item&quot;:&quot;hpt_crimescanner_size0_class5&quot;, &quot;Power&quot;:3.200000, &quot;Priority&quot;:0 }, 
        ///{ &quot;Slot&quot;:&quot;Slot02_Size4&quot;, &quot;Item&quot;:&quot;int_shieldcellbank_size4_class4&quot;, &quot;Power&quot;:1.480000, &quot;Priority&quot;:0 }, 
        ///{ &quot;Slot&quot;:&quot;Slot03_Size4&quot;, &quot;Item&quot;:&quot;int_shieldcellbank_size4_class4&quot;, &quot;Power&quot;:1.480000, &quot;Priority [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModulesInfo {
            get {
                return ResourceManager.GetString("ModulesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Items&quot;:[ 
        ///{ &quot;id&quot;:128049430, &quot;Name&quot;:&quot;hpt_beamlaser_fixed_large&quot;, &quot;BuyPrice&quot;:1177600 }, 
        ///{ &quot;id&quot;:128049434, &quot;Name&quot;:&quot;hpt_beamlaser_gimbal_large&quot;, &quot;BuyPrice&quot;:2396160 }, 
        ///{ &quot;id&quot;:128049437, &quot;Name&quot;:&quot;hpt_beamlaser_turret_large&quot;, &quot;BuyPrice&quot;:19399600 }, 
        ///{ &quot;id&quot;:128049436, &quot;Name&quot;:&quot;hpt_beamlaser_turret_medium&quot;, &quot;BuyPrice&quot;:2099900 }, 
        ///{ &quot;id&quot;:128049435, &quot;Name&quot;:&quot;hpt_beamlaser_turret_small&quot;, &quot;BuyPrice&quot;:500000 }, 
        ///{ &quot;id&quot;:128049428, &quot;Name&quot;:&quot;hpt_beamlaser_fixed_small&quot;, &quot;BuyPrice&quot;:37430 }, 
        ///{ &quot;id&quot;:128049429, &quot;Name&quot;:&quot;hpt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Outfitting {
            get {
                return ResourceManager.GetString("Outfitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;PriceList&quot;:[ 
        ///{ &quot;id&quot;:128049249, &quot;ShipType&quot;:&quot;sidewinder&quot;, &quot;ShipPrice&quot;:32000 }, 
        ///{ &quot;id&quot;:128049255, &quot;ShipType&quot;:&quot;eagle&quot;, &quot;ShipPrice&quot;:44800 }, 
        ///{ &quot;id&quot;:128049261, &quot;ShipType&quot;:&quot;hauler&quot;, &quot;ShipPrice&quot;:52720 }, 
        ///{ &quot;id&quot;:128049267, &quot;ShipType&quot;:&quot;adder&quot;, &quot;ShipPrice&quot;:87808 }, 
        ///{ &quot;id&quot;:128672138, &quot;ShipType&quot;:&quot;empire_eagle&quot;, &quot;ShipType_Localised&quot;:&quot;Imperial Eagle&quot;, &quot;ShipPrice&quot;:110825 }, 
        ///{ &quot;id&quot;:128049273, &quot;ShipType&quot;:&quot;viper&quot;, &quot;ShipType_Localised&quot;:&quot;Viper MkIII&quot;, &quot;ShipPrice&quot;:142931 }, 
        ///{ &quot;id&quot;:128049279, &quot;ShipType&quot;:&quot;cobramkiii [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Shipyard {
            get {
                return ResourceManager.GetString("Shipyard", resourceCulture);
            }
        }
    }
}
