//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDiscovery.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDDiscovery.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development, Release, Videos by:
        ///Cmdr Robby
        ///
        ///Developers for this release series:
        ///Eahlstan, Jugom, Flynn
        ///
        ///Images Captured by:
        ///Spandino, Robby, Eahlstan, Ettanin, CompleteNOOB from Frontier Elite Dangerous Images (C) Frontier Developments PLC
        ///
        ///Languages Translations:
        ///Eahlstan, Jugom, Fito-wolf, Dr.Smile, Keath Milligan, Kmizole, Potatossuaro, Zafford, Andrea Spada, Goscickiw, Nats-ji, Jay
        ///
        ///Program Concept by:
        ///Cmdr Finwen  (Robert Wahlström)
        ///
        ///Previous Contributors:
        ///Merovech, Bravada Cadelanne,  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EDCD {
            get {
                object obj = ResourceManager.GetObject("EDCD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELITE DANGEROUS DISCOVERY TERMS AND CONDITIONS â€“ December 2023
        ///1. This code is licensed under the Apache License Version 2.0, January 2004.  See below for the Apache license.
        ///2. DOWNLOADING OF DATA FROM GITHUB.COM/EDDISCOVERY.  From this site, EDD automatically checks at start up for the following information: New releases, Updated Bookmarks, New Expeditions, New Exploration list files, Updated Maps, Notifications.  It automatically downloads to your APPDATA folder any new or updated files detected.  No [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EDD_Licence_Mono {
            get {
                return ResourceManager.GetString("EDD_Licence_Mono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch31506\stshfhich31506\stshfbi31506\deflang2057\deflangfe2057\themelang2057\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset0\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        ///{\f37\fbidi \fswiss\fcharset0\fprq2{\*\panose 020f0502020204030204}Calibri;}{\flomajor\f31500\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EDD_License {
            get {
                return ResourceManager.GetString("EDD_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon edlogo_3mo_icon {
            get {
                object obj = ResourceManager.GetObject("edlogo_3mo_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EliteGalacticRegions {
            get {
                object obj = ResourceManager.GetObject("EliteGalacticRegions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aemonz EQ-Y e1899,,4549.96875,-850.5625,33732.375
        ///Aemonz WP-X e1-230 ,,3852.90625,-321.15625,33901.03125
        ///Aemonz WZ-Y e2137 ,,3857.34375,-576.5,33733.875
        ///Aemonz YK-P e5-68 ,,3865.3125,-1287.53125,34537.0625
        ///Aemorrs CG-O e6-2183,,2312.8125,-816.8125,34644.40625
        ///Aemorrs FB-X e1-3356,,1805.8125,-792.78125,33828.25
        ///Aemorrs HX-T e3-4455 ,,1531.46875,-409.75,34137.8125
        ///Aemorrs HX-T e3-4517 ,,1470.34375,-469.34375,34159.25
        ///Aemorrs KW-W e1-4401,,2241.3125,-840.40625,33926.3125
        ///Aemorrs LC-U e3-1611,,2378.968 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Marx_Nebula_List_14_06_25 {
            get {
                return ResourceManager.GetString("Marx_Nebula_List_14_06_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19 Phi-2 Ceti,&quot;CMDR Ziljan recommends this tourist destination as &quot;&quot;A little known gem in an inhabited, ringed, Earth-like world, discovered in the heart of the human bubble, orbiting a blue ringed gas giant.&quot;&quot;&quot;,-12.31,-49.22,-8.28
        ///2MASS J02351897+6131236,This system was recommended as a must see destination by Commander Draco25240 for its bountiful collection of stars.,-4192.72,114.50,-4190.63
        ///64 Piscium,&quot;Commander Demilikos suggests this magnificent vista with multiple stars in close vicinity, and just  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TouristBeacons {
            get {
                return ResourceManager.GetString("TouristBeacons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://coriolis.io/import?.
        /// </summary>
        public static string URLCoriolis {
            get {
                return ResourceManager.GetString("URLCoriolis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://edcd.github.io/.
        /// </summary>
        public static string URLEDCD {
            get {
                return ResourceManager.GetString("URLEDCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.elitedangerous.com/.
        /// </summary>
        public static string URLEDHomepage {
            get {
                return ResourceManager.GetString("URLEDHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.edshipyard.com/.
        /// </summary>
        public static string URLEDShipyard {
            get {
                return ResourceManager.GetString("URLEDShipyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.edsm.net/.
        /// </summary>
        public static string URLedsm {
            get {
                return ResourceManager.GetString("URLedsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.edsm.net/dump/systemsWithCoordinates.json.gz.
        /// </summary>
        public static string URLEDSMFullSystems {
            get {
                return ResourceManager.GetString("URLEDSMFullSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.github.com/repos/EDDiscovery/EDDiscoveryData/.
        /// </summary>
        public static string URLGithubDataDownload {
            get {
                return ResourceManager.GetString("URLGithubDataDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.github.com/repos/EDDiscovery/EDDiscovery/.
        /// </summary>
        public static string URLGithubDownload {
            get {
                return ResourceManager.GetString("URLGithubDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://discordapp.com/invite/0qIqfCQbziTWzsQu.
        /// </summary>
        public static string URLProjectDiscord {
            get {
                return ResourceManager.GetString("URLProjectDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://forums.frontier.co.uk/threads/eddiscovery-journals-exploration-trading-voice-recognition-speech-star-maps-webserver.329643/.
        /// </summary>
        public static string URLProjectEDForumPost {
            get {
                return ResourceManager.GetString("URLProjectEDForumPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/EDDiscovery/EDDiscovery/issues.
        /// </summary>
        public static string URLProjectFeedback {
            get {
                return ResourceManager.GetString("URLProjectFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/EDDiscovery/EDDiscovery.
        /// </summary>
        public static string URLProjectGithub {
            get {
                return ResourceManager.GetString("URLProjectGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/channel/UC6CMbualdRleR47ocYPnokg/.
        /// </summary>
        public static string URLProjectVideos {
            get {
                return ResourceManager.GetString("URLProjectVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com.
        /// </summary>
        public static string URLProjectVideosRoot {
            get {
                return ResourceManager.GetString("URLProjectVideosRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/EDDiscovery/EDDiscovery/wiki.
        /// </summary>
        public static string URLProjectWiki {
            get {
                return ResourceManager.GetString("URLProjectWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/embed/fSnxTDL90B4.
        /// </summary>
        public static string URLReleaseVideo {
            get {
                return ResourceManager.GetString("URLReleaseVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://downloads.spansh.co.uk/systems{0}.json.gz.
        /// </summary>
        public static string URLSpanshSystemsRoot {
            get {
                return ResourceManager.GetString("URLSpanshSystemsRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.microsoft.com/en-us/microsoft-edge/webview2/.
        /// </summary>
        public static string URLWebView2 {
            get {
                return ResourceManager.GetString("URLWebView2", resourceCulture);
            }
        }
    }
}
