/*
 * Copyright © 2016 - 2017 EDDiscovery development team
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
 * ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 * 
 * EDDiscovery is not affiliated with Frontier Developments plc.
 */
using System;
using System.Windows.Forms;

namespace EDDiscovery.UserControls
{
    partial class UserControlMap
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea2 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.Series series102 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series103 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series104 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series105 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series106 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series107 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series108 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series109 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series110 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series111 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series112 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series113 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series114 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series115 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series116 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series117 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series118 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series119 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series120 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series121 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series122 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series123 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series124 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series125 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series126 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series127 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series128 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series129 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series130 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series131 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series132 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series133 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series134 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series135 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series136 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series137 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series138 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series139 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series140 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series141 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series142 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series143 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series144 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series145 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series146 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series147 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series148 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series149 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series150 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series151 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series152 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series153 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series154 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series155 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series156 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series157 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series158 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series159 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series160 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series161 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series162 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series163 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series164 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series165 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series166 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series167 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series168 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series169 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series170 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series171 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series172 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series173 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series174 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series175 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series176 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series177 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series178 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series179 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series180 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series181 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series182 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series183 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series184 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series185 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series186 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series187 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series188 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series189 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series190 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series191 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series192 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series193 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series194 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series195 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series196 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series197 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series198 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series199 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series200 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series201 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.Series series202 = new System.Windows.Forms.DataVisualization.Charting.Series();
            this.labelExt1 = new System.Windows.Forms.Label();
            this.textMinRadius = new ExtendedControls.TextBoxBorder();
            this.labelExt3 = new System.Windows.Forms.Label();
            this.textMaxRadius = new ExtendedControls.TextBoxBorder();
            this.panelTop = new System.Windows.Forms.Panel();
            this.buttonExt1 = new ExtendedControls.ButtonExt();
            this.slideMaxItems = new System.Windows.Forms.TrackBar();
            this.chartMap = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.toolTip = new System.Windows.Forms.ToolTip(this.components);
            this.contextMenuStrip1 = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.zoomToolStripCenterOnMouse = new System.Windows.Forms.ToolStripMenuItem();
            this.centerOnMapToolCenterOnMap = new System.Windows.Forms.ToolStripMenuItem();
            this.panelTop.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.slideMaxItems)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartMap)).BeginInit();
            this.contextMenuStrip1.SuspendLayout();
            this.SuspendLayout();
            // 
            // labelExt1
            // 
            this.labelExt1.AutoSize = true;
            this.labelExt1.Location = new System.Drawing.Point(3, 6);
            this.labelExt1.Name = "labelExt1";
            this.labelExt1.Size = new System.Drawing.Size(24, 13);
            this.labelExt1.TabIndex = 3;
            this.labelExt1.Text = "Min";
            // 
            // textMinRadius
            // 
            this.textMinRadius.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textMinRadius.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textMinRadius.BorderColor = System.Drawing.Color.Transparent;
            this.textMinRadius.BorderColorScaling = 0.5F;
            this.textMinRadius.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.textMinRadius.ControlBackground = System.Drawing.SystemColors.Control;
            this.textMinRadius.Location = new System.Drawing.Point(28, 3);
            this.textMinRadius.Multiline = false;
            this.textMinRadius.Name = "textMinRadius";
            this.textMinRadius.ReadOnly = false;
            this.textMinRadius.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textMinRadius.SelectionLength = 0;
            this.textMinRadius.SelectionStart = 0;
            this.textMinRadius.Size = new System.Drawing.Size(40, 20);
            this.textMinRadius.TabIndex = 1;
            this.textMinRadius.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textMinRadius.WordWrap = true;
            this.textMinRadius.TextChanged += new System.EventHandler(this.TextMinRadius_TextChanged);
            // 
            // labelExt3
            // 
            this.labelExt3.AutoSize = true;
            this.labelExt3.Location = new System.Drawing.Point(78, 6);
            this.labelExt3.Name = "labelExt3";
            this.labelExt3.Size = new System.Drawing.Size(27, 13);
            this.labelExt3.TabIndex = 3;
            this.labelExt3.Text = "Max";
            // 
            // textMaxRadius
            // 
            this.textMaxRadius.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textMaxRadius.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textMaxRadius.BorderColor = System.Drawing.Color.Transparent;
            this.textMaxRadius.BorderColorScaling = 0.5F;
            this.textMaxRadius.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.textMaxRadius.ControlBackground = System.Drawing.SystemColors.Control;
            this.textMaxRadius.Location = new System.Drawing.Point(106, 3);
            this.textMaxRadius.Multiline = false;
            this.textMaxRadius.Name = "textMaxRadius";
            this.textMaxRadius.ReadOnly = false;
            this.textMaxRadius.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textMaxRadius.SelectionLength = 0;
            this.textMaxRadius.SelectionStart = 0;
            this.textMaxRadius.Size = new System.Drawing.Size(40, 20);
            this.textMaxRadius.TabIndex = 1;
            this.textMaxRadius.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textMaxRadius.WordWrap = true;
            this.textMaxRadius.TextChanged += new System.EventHandler(this.TextMaxRadius_TextChanged);
            // 
            // panelTop
            // 
            this.panelTop.BackColor = System.Drawing.SystemColors.Control;
            this.panelTop.Controls.Add(this.buttonExt1);
            this.panelTop.Controls.Add(this.slideMaxItems);
            this.panelTop.Controls.Add(this.labelExt1);
            this.panelTop.Controls.Add(this.textMinRadius);
            this.panelTop.Controls.Add(this.labelExt3);
            this.panelTop.Controls.Add(this.textMaxRadius);
            this.panelTop.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelTop.Location = new System.Drawing.Point(0, 0);
            this.panelTop.Name = "panelTop";
            this.panelTop.Size = new System.Drawing.Size(380, 26);
            this.panelTop.TabIndex = 25;
            this.toolTip.SetToolTip(this.panelTop, "Rotate with 1st mouse button; Zoom with ScrollWheel; Pan with WASD");
            // 
            // buttonExt1
            // 
            this.buttonExt1.Dock = System.Windows.Forms.DockStyle.Right;
            this.buttonExt1.Location = new System.Drawing.Point(264, 0);
            this.buttonExt1.Name = "buttonExt1";
            this.buttonExt1.Size = new System.Drawing.Size(26, 26);
            this.buttonExt1.TabIndex = 5;
            this.buttonExt1.Text = "Z";
            this.buttonExt1.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.buttonExt1.UseVisualStyleBackColor = true;
            // 
            // slideMaxItems
            // 
            this.slideMaxItems.Dock = System.Windows.Forms.DockStyle.Right;
            this.slideMaxItems.LargeChange = 50;
            this.slideMaxItems.Location = new System.Drawing.Point(290, 0);
            this.slideMaxItems.Maximum = 500;
            this.slideMaxItems.Minimum = 50;
            this.slideMaxItems.Name = "slideMaxItems";
            this.slideMaxItems.Size = new System.Drawing.Size(90, 26);
            this.slideMaxItems.SmallChange = 10;
            this.slideMaxItems.TabIndex = 4;
            this.slideMaxItems.TickFrequency = 50;
            this.slideMaxItems.Value = 250;
            this.slideMaxItems.Scroll += new System.EventHandler(this.SlideMaxItems_Scroll);
            this.slideMaxItems.MouseHover += new System.EventHandler(this.SlideMaxItems_MouseHover);
            // 
            // chartMap
            // 
            this.chartMap.BackColor = System.Drawing.Color.Black;
            this.chartMap.BackSecondaryColor = System.Drawing.Color.Transparent;
            this.chartMap.BorderSkin.BorderColor = System.Drawing.Color.White;
            chartArea2.Area3DStyle.Enable3D = true;
            chartArea2.Area3DStyle.Inclination = 20;
            chartArea2.Area3DStyle.IsRightAngleAxes = false;
            chartArea2.Area3DStyle.Perspective = 7;
            chartArea2.Area3DStyle.Rotation = 20;
            chartArea2.Area3DStyle.WallWidth = 0;
            chartArea2.AxisX.LabelStyle.ForeColor = System.Drawing.Color.White;
            chartArea2.AxisX.LineColor = System.Drawing.Color.White;
            chartArea2.AxisX.MajorGrid.Interval = 0D;
            chartArea2.AxisX.MajorGrid.LineColor = System.Drawing.Color.Gray;
            chartArea2.AxisX.MajorTickMark.LineColor = System.Drawing.Color.Gray;
            chartArea2.AxisX.MinorGrid.LineColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            chartArea2.AxisX.TextOrientation = System.Windows.Forms.DataVisualization.Charting.TextOrientation.Horizontal;
            chartArea2.AxisX.Title = "X";
            chartArea2.AxisX.TitleForeColor = System.Drawing.Color.White;
            chartArea2.AxisX2.LabelStyle.ForeColor = System.Drawing.Color.White;
            chartArea2.AxisX2.LineColor = System.Drawing.Color.White;
            chartArea2.AxisX2.MajorGrid.Interval = 0D;
            chartArea2.AxisX2.MajorGrid.LineColor = System.Drawing.Color.Gray;
            chartArea2.AxisX2.MinorGrid.LineColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            chartArea2.AxisX2.TextOrientation = System.Windows.Forms.DataVisualization.Charting.TextOrientation.Horizontal;
            chartArea2.AxisX2.Title = "Y";
            chartArea2.AxisX2.TitleForeColor = System.Drawing.Color.White;
            chartArea2.AxisY.LabelStyle.ForeColor = System.Drawing.Color.White;
            chartArea2.AxisY.LineColor = System.Drawing.Color.White;
            chartArea2.AxisY.MajorGrid.Interval = 0D;
            chartArea2.AxisY.MajorGrid.LineColor = System.Drawing.Color.Gray;
            chartArea2.AxisY.MajorTickMark.LineColor = System.Drawing.Color.Gray;
            chartArea2.AxisY.MinorGrid.LineColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            chartArea2.AxisY.TextOrientation = System.Windows.Forms.DataVisualization.Charting.TextOrientation.Horizontal;
            chartArea2.AxisY.Title = "Z";
            chartArea2.AxisY.TitleForeColor = System.Drawing.Color.White;
            chartArea2.AxisY2.LabelStyle.ForeColor = System.Drawing.Color.White;
            chartArea2.AxisY2.LineColor = System.Drawing.Color.White;
            chartArea2.AxisY2.MajorGrid.Interval = 0D;
            chartArea2.AxisY2.MajorGrid.LineColor = System.Drawing.Color.Gray;
            chartArea2.AxisY2.MinorGrid.LineColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            chartArea2.AxisY2.TextOrientation = System.Windows.Forms.DataVisualization.Charting.TextOrientation.Horizontal;
            chartArea2.AxisY2.Title = "Y";
            chartArea2.AxisY2.TitleForeColor = System.Drawing.Color.White;
            chartArea2.BackColor = System.Drawing.Color.Black;
            chartArea2.BackSecondaryColor = System.Drawing.Color.Black;
            chartArea2.Name = "ChartArea";
            this.chartMap.ChartAreas.Add(chartArea2);
            this.chartMap.Location = new System.Drawing.Point(15, 41);
            this.chartMap.Margin = new System.Windows.Forms.Padding(0);
            this.chartMap.MinimumSize = new System.Drawing.Size(50, 50);
            this.chartMap.Name = "chartMap";
            series102.ChartArea = "ChartArea";
            series102.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series102.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series102.MarkerSize = 3;
            series102.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series102.Name = "Series1";
            series103.ChartArea = "ChartArea";
            series103.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series103.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series103.MarkerSize = 3;
            series103.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series103.Name = "Series2";
            series104.ChartArea = "ChartArea";
            series104.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series104.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series104.MarkerSize = 3;
            series104.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series104.Name = "Series3";
            series105.ChartArea = "ChartArea";
            series105.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series105.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series105.MarkerSize = 3;
            series105.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series105.Name = "Series4";
            series106.ChartArea = "ChartArea";
            series106.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series106.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series106.MarkerSize = 3;
            series106.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series106.Name = "Series5";
            series107.ChartArea = "ChartArea";
            series107.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series107.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series107.MarkerSize = 3;
            series107.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series107.Name = "Series6";
            series108.ChartArea = "ChartArea";
            series108.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series108.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series108.MarkerSize = 3;
            series108.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series108.Name = "Series7";
            series109.ChartArea = "ChartArea";
            series109.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series109.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series109.MarkerSize = 3;
            series109.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series109.Name = "Series8";
            series110.ChartArea = "ChartArea";
            series110.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series110.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series110.MarkerSize = 3;
            series110.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series110.Name = "Series9";
            series111.ChartArea = "ChartArea";
            series111.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series111.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series111.MarkerSize = 3;
            series111.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series111.Name = "Series10";
            series112.ChartArea = "ChartArea";
            series112.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series112.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series112.MarkerSize = 3;
            series112.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series112.Name = "Series11";
            series113.ChartArea = "ChartArea";
            series113.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series113.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series113.MarkerSize = 3;
            series113.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series113.Name = "Series12";
            series114.ChartArea = "ChartArea";
            series114.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series114.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series114.MarkerSize = 3;
            series114.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series114.Name = "Series13";
            series115.ChartArea = "ChartArea";
            series115.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series115.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series115.MarkerSize = 3;
            series115.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series115.Name = "Series14";
            series116.ChartArea = "ChartArea";
            series116.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series116.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series116.MarkerSize = 3;
            series116.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series116.Name = "Series15";
            series117.ChartArea = "ChartArea";
            series117.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series117.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series117.MarkerSize = 3;
            series117.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series117.Name = "Series16";
            series118.ChartArea = "ChartArea";
            series118.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series118.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series118.MarkerSize = 3;
            series118.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series118.Name = "Series17";
            series119.ChartArea = "ChartArea";
            series119.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series119.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series119.MarkerSize = 3;
            series119.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series119.Name = "Series18";
            series120.ChartArea = "ChartArea";
            series120.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series120.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series120.MarkerSize = 3;
            series120.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series120.Name = "Series19";
            series121.ChartArea = "ChartArea";
            series121.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series121.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series121.MarkerSize = 3;
            series121.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series121.Name = "Series20";
            series122.ChartArea = "ChartArea";
            series122.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series122.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series122.MarkerSize = 3;
            series122.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series122.Name = "Series21";
            series123.ChartArea = "ChartArea";
            series123.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series123.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series123.MarkerSize = 3;
            series123.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series123.Name = "Series22";
            series124.ChartArea = "ChartArea";
            series124.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series124.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series124.MarkerSize = 3;
            series124.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series124.Name = "Series23";
            series125.ChartArea = "ChartArea";
            series125.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series125.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series125.MarkerSize = 3;
            series125.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series125.Name = "Series24";
            series126.ChartArea = "ChartArea";
            series126.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series126.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series126.MarkerSize = 3;
            series126.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series126.Name = "Series25";
            series127.ChartArea = "ChartArea";
            series127.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series127.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series127.MarkerSize = 3;
            series127.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series127.Name = "Series26";
            series128.ChartArea = "ChartArea";
            series128.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series128.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series128.MarkerSize = 3;
            series128.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series128.Name = "Series27";
            series129.ChartArea = "ChartArea";
            series129.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series129.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series129.MarkerSize = 3;
            series129.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series129.Name = "Series28";
            series130.ChartArea = "ChartArea";
            series130.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series130.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series130.MarkerSize = 3;
            series130.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series130.Name = "Series29";
            series131.ChartArea = "ChartArea";
            series131.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series131.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series131.MarkerSize = 3;
            series131.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series131.Name = "Series30";
            series132.ChartArea = "ChartArea";
            series132.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series132.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series132.MarkerSize = 3;
            series132.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series132.Name = "Series31";
            series133.ChartArea = "ChartArea";
            series133.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series133.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series133.MarkerSize = 3;
            series133.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series133.Name = "Series32";
            series134.ChartArea = "ChartArea";
            series134.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series134.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series134.MarkerSize = 3;
            series134.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series134.Name = "Series33";
            series135.ChartArea = "ChartArea";
            series135.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series135.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series135.MarkerSize = 3;
            series135.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series135.Name = "Series34";
            series136.ChartArea = "ChartArea";
            series136.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series136.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series136.MarkerSize = 3;
            series136.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series136.Name = "Series35";
            series137.ChartArea = "ChartArea";
            series137.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series137.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series137.MarkerSize = 3;
            series137.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series137.Name = "Series37";
            series138.ChartArea = "ChartArea";
            series138.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series138.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series138.MarkerSize = 3;
            series138.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series138.Name = "Series38";
            series139.ChartArea = "ChartArea";
            series139.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series139.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series139.MarkerSize = 3;
            series139.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series139.Name = "Series39";
            series140.ChartArea = "ChartArea";
            series140.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series140.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series140.MarkerSize = 3;
            series140.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series140.Name = "Series40";
            series141.ChartArea = "ChartArea";
            series141.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series141.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series141.MarkerSize = 3;
            series141.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series141.Name = "Series41";
            series142.ChartArea = "ChartArea";
            series142.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series142.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series142.MarkerSize = 3;
            series142.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series142.Name = "Series42";
            series143.ChartArea = "ChartArea";
            series143.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series143.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series143.MarkerSize = 3;
            series143.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series143.Name = "Series43";
            series144.ChartArea = "ChartArea";
            series144.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series144.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series144.MarkerSize = 3;
            series144.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series144.Name = "Series44";
            series145.ChartArea = "ChartArea";
            series145.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series145.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series145.MarkerSize = 3;
            series145.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series145.Name = "Series45";
            series146.ChartArea = "ChartArea";
            series146.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series146.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series146.MarkerSize = 3;
            series146.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series146.Name = "Series46";
            series147.ChartArea = "ChartArea";
            series147.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series147.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series147.MarkerSize = 3;
            series147.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series147.Name = "Series47";
            series148.ChartArea = "ChartArea";
            series148.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series148.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series148.MarkerSize = 3;
            series148.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series148.Name = "Series48";
            series149.ChartArea = "ChartArea";
            series149.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series149.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series149.MarkerSize = 3;
            series149.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series149.Name = "Series49";
            series150.ChartArea = "ChartArea";
            series150.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series150.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series150.MarkerSize = 3;
            series150.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series150.Name = "Series50";
            series151.ChartArea = "ChartArea";
            series151.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series151.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series151.MarkerSize = 3;
            series151.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series151.Name = "Series51";
            series152.ChartArea = "ChartArea";
            series152.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series152.MarkerColor = System.Drawing.Color.Red;
            series152.MarkerSize = 6;
            series152.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series152.Name = "Center";
            series153.ChartArea = "ChartArea";
            series153.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series153.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series153.MarkerSize = 3;
            series153.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series153.Name = "Series53";
            series154.ChartArea = "ChartArea";
            series154.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series154.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series154.MarkerSize = 3;
            series154.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series154.Name = "Series54";
            series155.ChartArea = "ChartArea";
            series155.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series155.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series155.MarkerSize = 3;
            series155.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series155.Name = "Series55";
            series156.ChartArea = "ChartArea";
            series156.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series156.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series156.MarkerSize = 3;
            series156.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series156.Name = "Series56";
            series157.ChartArea = "ChartArea";
            series157.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series157.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series157.MarkerSize = 3;
            series157.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series157.Name = "Series57";
            series158.ChartArea = "ChartArea";
            series158.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series158.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series158.MarkerSize = 3;
            series158.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series158.Name = "Series58";
            series159.ChartArea = "ChartArea";
            series159.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series159.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series159.MarkerSize = 3;
            series159.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series159.Name = "Series59";
            series160.ChartArea = "ChartArea";
            series160.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series160.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series160.MarkerSize = 3;
            series160.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series160.Name = "Series60";
            series161.ChartArea = "ChartArea";
            series161.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series161.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series161.MarkerSize = 3;
            series161.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series161.Name = "Series61";
            series162.ChartArea = "ChartArea";
            series162.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series162.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series162.MarkerSize = 3;
            series162.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series162.Name = "Series62";
            series163.ChartArea = "ChartArea";
            series163.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series163.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series163.MarkerSize = 3;
            series163.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series163.Name = "Series63";
            series164.ChartArea = "ChartArea";
            series164.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series164.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series164.MarkerSize = 3;
            series164.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series164.Name = "Series64";
            series165.ChartArea = "ChartArea";
            series165.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series165.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series165.MarkerSize = 3;
            series165.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series165.Name = "Series65";
            series166.ChartArea = "ChartArea";
            series166.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series166.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series166.MarkerSize = 3;
            series166.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series166.Name = "Series66";
            series167.ChartArea = "ChartArea";
            series167.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series167.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series167.MarkerSize = 3;
            series167.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series167.Name = "Series67";
            series168.ChartArea = "ChartArea";
            series168.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series168.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series168.MarkerSize = 3;
            series168.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series168.Name = "Series68";
            series169.ChartArea = "ChartArea";
            series169.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series169.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series169.MarkerSize = 3;
            series169.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series169.Name = "Series69";
            series170.ChartArea = "ChartArea";
            series170.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series170.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series170.MarkerSize = 3;
            series170.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series170.Name = "Series70";
            series171.ChartArea = "ChartArea";
            series171.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series171.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series171.MarkerSize = 3;
            series171.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series171.Name = "Series71";
            series172.ChartArea = "ChartArea";
            series172.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series172.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series172.MarkerSize = 3;
            series172.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series172.Name = "Series72";
            series173.ChartArea = "ChartArea";
            series173.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series173.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series173.MarkerSize = 3;
            series173.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series173.Name = "Series73";
            series174.ChartArea = "ChartArea";
            series174.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series174.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series174.MarkerSize = 3;
            series174.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series174.Name = "Series74";
            series175.ChartArea = "ChartArea";
            series175.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series175.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series175.MarkerSize = 3;
            series175.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series175.Name = "Series75";
            series176.ChartArea = "ChartArea";
            series176.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series176.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series176.MarkerSize = 3;
            series176.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series176.Name = "Series76";
            series177.ChartArea = "ChartArea";
            series177.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series177.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series177.MarkerSize = 3;
            series177.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series177.Name = "Series77";
            series178.ChartArea = "ChartArea";
            series178.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series178.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series178.MarkerSize = 3;
            series178.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series178.Name = "Series78";
            series179.ChartArea = "ChartArea";
            series179.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series179.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series179.MarkerSize = 3;
            series179.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series179.Name = "Series79";
            series180.ChartArea = "ChartArea";
            series180.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series180.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series180.MarkerSize = 3;
            series180.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series180.Name = "Series80";
            series181.ChartArea = "ChartArea";
            series181.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series181.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series181.MarkerSize = 3;
            series181.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series181.Name = "Series81";
            series182.ChartArea = "ChartArea";
            series182.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series182.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series182.MarkerSize = 3;
            series182.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series182.Name = "Series82";
            series183.ChartArea = "ChartArea";
            series183.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series183.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series183.MarkerSize = 3;
            series183.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series183.Name = "Series83";
            series184.ChartArea = "ChartArea";
            series184.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series184.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series184.MarkerSize = 3;
            series184.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series184.Name = "Series84";
            series185.ChartArea = "ChartArea";
            series185.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series185.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series185.MarkerSize = 3;
            series185.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series185.Name = "Series85";
            series186.ChartArea = "ChartArea";
            series186.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series186.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series186.MarkerSize = 3;
            series186.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series186.Name = "Series86";
            series187.ChartArea = "ChartArea";
            series187.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series187.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series187.MarkerSize = 3;
            series187.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series187.Name = "Series87";
            series188.ChartArea = "ChartArea";
            series188.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series188.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series188.MarkerSize = 3;
            series188.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series188.Name = "Series88";
            series189.ChartArea = "ChartArea";
            series189.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series189.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series189.MarkerSize = 3;
            series189.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series189.Name = "Series89";
            series190.ChartArea = "ChartArea";
            series190.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series190.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series190.MarkerSize = 3;
            series190.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series190.Name = "Series90";
            series191.ChartArea = "ChartArea";
            series191.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series191.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series191.MarkerSize = 3;
            series191.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series191.Name = "Series91";
            series192.ChartArea = "ChartArea";
            series192.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series192.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series192.MarkerSize = 3;
            series192.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series192.Name = "Series92";
            series193.ChartArea = "ChartArea";
            series193.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series193.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series193.MarkerSize = 3;
            series193.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series193.Name = "Series93";
            series194.ChartArea = "ChartArea";
            series194.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series194.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series194.MarkerSize = 3;
            series194.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series194.Name = "Series94";
            series195.ChartArea = "ChartArea";
            series195.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series195.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series195.MarkerSize = 3;
            series195.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series195.Name = "Series95";
            series196.ChartArea = "ChartArea";
            series196.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series196.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series196.MarkerSize = 3;
            series196.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series196.Name = "Series96";
            series197.ChartArea = "ChartArea";
            series197.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series197.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series197.MarkerSize = 3;
            series197.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series197.Name = "Series97";
            series198.ChartArea = "ChartArea";
            series198.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series198.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series198.MarkerSize = 3;
            series198.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series198.Name = "Series98";
            series199.ChartArea = "ChartArea";
            series199.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series199.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series199.MarkerSize = 3;
            series199.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series199.Name = "Series99";
            series200.ChartArea = "ChartArea";
            series200.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series200.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series200.MarkerSize = 3;
            series200.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series200.Name = "Series100";
            series201.ChartArea = "ChartArea";
            series201.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series201.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series201.MarkerSize = 3;
            series201.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series201.Name = "Series101";
            series202.ChartArea = "ChartArea";
            series202.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Point;
            series202.MarkerColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            series202.MarkerSize = 3;
            series202.MarkerStyle = System.Windows.Forms.DataVisualization.Charting.MarkerStyle.Circle;
            series202.Name = "Series102";
            this.chartMap.Series.Add(series102);
            this.chartMap.Series.Add(series103);
            this.chartMap.Series.Add(series104);
            this.chartMap.Series.Add(series105);
            this.chartMap.Series.Add(series106);
            this.chartMap.Series.Add(series107);
            this.chartMap.Series.Add(series108);
            this.chartMap.Series.Add(series109);
            this.chartMap.Series.Add(series110);
            this.chartMap.Series.Add(series111);
            this.chartMap.Series.Add(series112);
            this.chartMap.Series.Add(series113);
            this.chartMap.Series.Add(series114);
            this.chartMap.Series.Add(series115);
            this.chartMap.Series.Add(series116);
            this.chartMap.Series.Add(series117);
            this.chartMap.Series.Add(series118);
            this.chartMap.Series.Add(series119);
            this.chartMap.Series.Add(series120);
            this.chartMap.Series.Add(series121);
            this.chartMap.Series.Add(series122);
            this.chartMap.Series.Add(series123);
            this.chartMap.Series.Add(series124);
            this.chartMap.Series.Add(series125);
            this.chartMap.Series.Add(series126);
            this.chartMap.Series.Add(series127);
            this.chartMap.Series.Add(series128);
            this.chartMap.Series.Add(series129);
            this.chartMap.Series.Add(series130);
            this.chartMap.Series.Add(series131);
            this.chartMap.Series.Add(series132);
            this.chartMap.Series.Add(series133);
            this.chartMap.Series.Add(series134);
            this.chartMap.Series.Add(series135);
            this.chartMap.Series.Add(series136);
            this.chartMap.Series.Add(series137);
            this.chartMap.Series.Add(series138);
            this.chartMap.Series.Add(series139);
            this.chartMap.Series.Add(series140);
            this.chartMap.Series.Add(series141);
            this.chartMap.Series.Add(series142);
            this.chartMap.Series.Add(series143);
            this.chartMap.Series.Add(series144);
            this.chartMap.Series.Add(series145);
            this.chartMap.Series.Add(series146);
            this.chartMap.Series.Add(series147);
            this.chartMap.Series.Add(series148);
            this.chartMap.Series.Add(series149);
            this.chartMap.Series.Add(series150);
            this.chartMap.Series.Add(series151);
            this.chartMap.Series.Add(series152);
            this.chartMap.Series.Add(series153);
            this.chartMap.Series.Add(series154);
            this.chartMap.Series.Add(series155);
            this.chartMap.Series.Add(series156);
            this.chartMap.Series.Add(series157);
            this.chartMap.Series.Add(series158);
            this.chartMap.Series.Add(series159);
            this.chartMap.Series.Add(series160);
            this.chartMap.Series.Add(series161);
            this.chartMap.Series.Add(series162);
            this.chartMap.Series.Add(series163);
            this.chartMap.Series.Add(series164);
            this.chartMap.Series.Add(series165);
            this.chartMap.Series.Add(series166);
            this.chartMap.Series.Add(series167);
            this.chartMap.Series.Add(series168);
            this.chartMap.Series.Add(series169);
            this.chartMap.Series.Add(series170);
            this.chartMap.Series.Add(series171);
            this.chartMap.Series.Add(series172);
            this.chartMap.Series.Add(series173);
            this.chartMap.Series.Add(series174);
            this.chartMap.Series.Add(series175);
            this.chartMap.Series.Add(series176);
            this.chartMap.Series.Add(series177);
            this.chartMap.Series.Add(series178);
            this.chartMap.Series.Add(series179);
            this.chartMap.Series.Add(series180);
            this.chartMap.Series.Add(series181);
            this.chartMap.Series.Add(series182);
            this.chartMap.Series.Add(series183);
            this.chartMap.Series.Add(series184);
            this.chartMap.Series.Add(series185);
            this.chartMap.Series.Add(series186);
            this.chartMap.Series.Add(series187);
            this.chartMap.Series.Add(series188);
            this.chartMap.Series.Add(series189);
            this.chartMap.Series.Add(series190);
            this.chartMap.Series.Add(series191);
            this.chartMap.Series.Add(series192);
            this.chartMap.Series.Add(series193);
            this.chartMap.Series.Add(series194);
            this.chartMap.Series.Add(series195);
            this.chartMap.Series.Add(series196);
            this.chartMap.Series.Add(series197);
            this.chartMap.Series.Add(series198);
            this.chartMap.Series.Add(series199);
            this.chartMap.Series.Add(series200);
            this.chartMap.Series.Add(series201);
            this.chartMap.Series.Add(series202);
            this.chartMap.Size = new System.Drawing.Size(350, 350);
            this.chartMap.SuppressExceptions = true;
            this.chartMap.TabIndex = 29;
            this.chartMap.Text = "chart2";
            this.chartMap.KeyDown += new System.Windows.Forms.KeyEventHandler(this.chartMap_KeyDown);
            this.chartMap.MouseDown += new System.Windows.Forms.MouseEventHandler(this.ChartMap_MouseDown);
            this.chartMap.MouseMove += new System.Windows.Forms.MouseEventHandler(this.ChartMap_MouseMove);
            this.chartMap.MouseUp += new System.Windows.Forms.MouseEventHandler(this.ChartMap_MouseUp);
            // 
            // contextMenuStrip1
            // 
            this.contextMenuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.zoomToolStripCenterOnMouse,
            this.centerOnMapToolCenterOnMap});
            this.contextMenuStrip1.Name = "contextMenuStrip1";
            this.contextMenuStrip1.Size = new System.Drawing.Size(166, 70);
            // 
            // zoomToolStripCenterOnMouse
            // 
            this.zoomToolStripCenterOnMouse.Name = "zoomToolStripCenterOnMouse";
            this.zoomToolStripCenterOnMouse.Size = new System.Drawing.Size(165, 22);
            this.zoomToolStripCenterOnMouse.Text = "Center on Mouse";
            this.zoomToolStripCenterOnMouse.Click += new System.EventHandler(this.zoomToolStripMenuItem_Click);
            // 
            // centerOnMapToolCenterOnMap
            // 
            this.centerOnMapToolCenterOnMap.Name = "centerOnMapToolCenterOnMap";
            this.centerOnMapToolCenterOnMap.Size = new System.Drawing.Size(165, 22);
            this.centerOnMapToolCenterOnMap.Text = "Center on Map";
            this.centerOnMapToolCenterOnMap.Click += new System.EventHandler(this.centerOnMapToolStripMenuItem1_Click);
            // 
            // UserControlMap
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Black;
            this.Controls.Add(this.panelTop);
            this.Controls.Add(this.chartMap);
            this.Name = "UserControlMap";
            this.Size = new System.Drawing.Size(380, 406);
            this.Load += new System.EventHandler(this.UserControlMap_Load);
            this.Resize += new System.EventHandler(this.UserControlMap_Resize);
            this.panelTop.ResumeLayout(false);
            this.panelTop.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.slideMaxItems)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartMap)).EndInit();
            this.contextMenuStrip1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion
        private System.Windows.Forms.Label labelExt1;
        private ExtendedControls.TextBoxBorder textMinRadius;
        private System.Windows.Forms.Label labelExt3;
        private ExtendedControls.TextBoxBorder textMaxRadius;
        private Panel panelTop;
        private System.Windows.Forms.DataVisualization.Charting.Chart chartMap;
        private TrackBar slideMaxItems;
        private ToolTip toolTip;
        private ExtendedControls.ButtonExt buttonExt1;
        private ContextMenuStrip contextMenuStrip1;
        private ToolStripMenuItem zoomToolStripCenterOnMouse;
        private ToolStripMenuItem centerOnMapToolCenterOnMap;
    }
}
